[package]
name = "santoso"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0.171"
validator = { version = "0.20.0", features = ["derive"] }